"""add driver id

Revision ID: 21e4bac08aef
Revises: 7564b1b0799a
Create Date: 2026-07-05 18:00:21.984629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21e4bac08aef'
down_revision: Union[str, Sequence[str], None] = '7564b1b0799a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('waste_reports', sa.Column('driver_id', sa.Integer(), nullable=True))
    op.alter_column('waste_reports', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('waste_reports', 'address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(None, 'waste_reports', 'users', ['driver_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'waste_reports', type_='foreignkey')
    op.alter_column('waste_reports', 'address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('waste_reports', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('waste_reports', 'driver_id')
    # ### end Alembic commands ###
