"""add latitude longitude

Revision ID: 7564b1b0799a
Revises: 2c9ff94d640b
Create Date: 2026-07-05 16:19:20.845907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7564b1b0799a'
down_revision: Union[str, Sequence[str], None] = '2c9ff94d640b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('waste_reports', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('waste_reports', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('waste_reports', 'longitude')
    op.drop_column('waste_reports', 'latitude')
    # ### end Alembic commands ###
